#!/bin/bash

trap 'exit' INT TERM ERR
trap 'kill -TERM 0' EXIT

# source ROS env
source /home/ros/.bashrc

# source workspace env
source ~/neuronbot2_ros2_ws/install/setup.bash

# put your ros2 launch commands here, and make sure append '&' symbol in the end of line
ros2 launch neuronbot2_bringup bringup_launch.py &
ros2 topic pub /cmd_vel geometry_msgs/msg/Twist '{linear: {x: 0.0, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 1.0}}' &

# wait until receive a terminating signal
wait
