#!/bin/bash

install_path="/opt/adlink/rmt"
user=$(logname)
sudo chmod a+x ${install_path}/agent_example
sudo chmod a+x ${install_path}/tasks/*
loginctl enable-linger $user
mkdir /home/$user/.config/systemd/user -p
cp ${install_path}/RMTagent.service /home/$user/.config/systemd/user

if pgrep -f '/lib/systemd/systemd --user' > /dev/null
then
    echo "loginctl user already enable"
else
    sudo -H -u $user bash -c 'export XDG_RUNTIME_DIR=/run/user/$UID;
        systemd --user 2>/dev/null;' 2> /dev/null &
fi

sudo chown -R $user /home/$user/.config/systemd
sudo -H -u $user bash -c 'export XDG_RUNTIME_DIR=/run/user/$UID;
    systemctl --user daemon-reload;
    systemctl --user enable RMTagent.service'
